...
#
# And lsm-put fails... even thought we got file size and adler32 checksum
# for second time just a second befere calling lsm-put
#
2016-11-15 01:48:03|120871|LocalSiteMov| Getting local File(/scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001) info.
2016-11-15 01:48:03|120871|LocalSiteMov| Executing getsize() for file: /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001
2016-11-15 01:48:03|120871|LocalSiteMov| Got file size: 78545334
2016-11-15 01:48:03|120871|LocalSiteMov| Executing adler32() for file: /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001
2016-11-15 01:48:03|120871|LocalSiteMov| Got adler32 checksum: 73ee77b7
2016-11-15 01:48:03|120871|LocalSiteMov| Executing command:  export X509_USER_PROXY=/home2/osg/usatlas1/home_bl_atlas-ce.bu.edu_9619_atlas-ce.bu.edu#753841.0#1479171385/bl_639a9c598ce7.proxy; lsm-put -t ATLASDATADISK --size 78545334 --checksum adler32:73ee77b7 --guid 7C28BCCD-E235-8A4D-B359-CA415246E571 /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001 srm://atlas.bu.edu:8443/srm/v2/server?SFN=/gpfs1/atlasdatadisk/rucio/panda/a2/0c/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001
2016-11-15 01:48:04|120871|LocalSiteMov| Command finished after 0.410000 s
2016-11-15 01:48:04|120871|LocalSiteMov| ec = 211, output = *** ERROR *** lsm status 211: command [/atlasgrid/osg-wn-1.0.0/lsm/lsm-put -t ATLASDATADISK --size 78545334 --checksum adler32:73ee77b7 --guid 7C28BCCD-E235-8A4D-B359-CA415246E571 /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001 srm://atlas.bu.edu:8443/srm/v2/server?SFN=/gpfs1/atlasdatadisk/rucio/panda/a2/0c/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001] failed with error: local source [/scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001] exists but is not a regular file 
2016-11-15 01:48:04|120871|LocalSiteMov| !!WARNING!!2990!! Command failed:  export X509_USER_PROXY=/home2/osg/usatlas1/home_bl_atlas-ce.bu.edu_9619_atlas-ce.bu.edu#753841.0#1479171385/bl_639a9c598ce7.proxy; lsm-put -t ATLASDATADISK --size 78545334 --checksum adler32:73ee77b7 --guid 7C28BCCD-E235-8A4D-B359-CA415246E571 /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001 srm://atlas.bu.edu:8443/srm/v2/server?SFN=/gpfs1/atlasdatadisk/rucio/panda/a2/0c/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001
2016-11-15 01:48:04|120871|LocalSiteMov| !!WARNING!!2990!! Stage Out failed: Status=211 Output=*** ERROR *** lsm status 211: command [/atlasgrid/osg-wn-1.0.0/lsm/lsm-put -t ATLASDATADISK --size 78545334 --checksum adler32:73ee77b7 --guid 7C28BCCD-E235-8A4D-B359-CA415246E571 /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001 srm://atlas.bu.edu:8443/srm/v2/server?SFN=/gpfs1/atlasdatadisk/rucio/panda/a2/0c/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001] failed with error: local source [/scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_001] exists but is not a regular file 
...
#
# Transfer failed so pilot start working area cleanup and keep just
# "important" files that will be later compressed in job log tarbal
# => during this step big output files are removed from working area
# (well I did not check directly sources but I guess "Cleaning up ..."
# means removing these files). In full log files there are directory
# listing after this step and these files are really gone.
#
2016-11-15 01:58:09|120346|JobLog.py   | This site does not support job recovery: HOLDING state reset to FAILED
2016-11-15 01:58:09|120346|JobLog.py   | Building log extracts..
2016-11-15 01:58:09|120871|RunJob.py   | job.workdir is /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229 pworkdir is /scratch/Panda_Pilot_120346_1479173221 
2016-11-15 01:58:09|120346|pUtil.py    | Job report could not be found in the payload stdout, will add the last 10 lines instead for the log extracts
2016-11-15 01:58:09|120346|ATLASExperim| Removing redundant files prior to log creation
2016-11-15 01:58:09|120346|ATLASExperim| Attempting to cleanup /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/athenaMP-workers-AODtoDAOD-a2da
2016-11-15 01:58:09|120346|ATLASExperim| Cleaning up /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/athenaMP-workers-AODtoDAOD-a2da/worker_7/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_000
2016-11-15 01:58:09|120346|ATLASExperim| Cleaning up /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/athenaMP-workers-AODtoDAOD-a2da/worker_0/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_000
2016-11-15 01:58:09|120346|ATLASExperim| Cleaning up /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/athenaMP-workers-AODtoDAOD-a2da/worker_4/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_000
2016-11-15 01:58:09|120346|ATLASExperim| Cleaning up /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/athenaMP-workers-AODtoDAOD-a2da/worker_6/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_000
2016-11-15 01:58:09|120346|ATLASExperim| Cleaning up /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/athenaMP-workers-AODtoDAOD-a2da/worker_3/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_000
2016-11-15 01:58:09|120346|ATLASExperim| Cleaning up /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/athenaMP-workers-AODtoDAOD-a2da/worker_1/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_000
2016-11-15 01:58:09|120346|ATLASExperim| Cleaning up /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/athenaMP-workers-AODtoDAOD-a2da/worker_2/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_000
2016-11-15 01:58:09|120346|ATLASExperim| Cleaning up /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/athenaMP-workers-AODtoDAOD-a2da/worker_5/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_000
2016-11-15 01:58:09|120346|ATLASExperim| Cleaning up /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229/athenaMP-workers-AODtoDAOD-a2da/evt_counter/DAOD_JETM3.09889908._000092.pool.root.1.panda.um_000
...
#
# Log files are created after the cleanup
#
2016-11-15 01:58:09|120346|JobLog.py   | Preparing to create log file
2016-11-15 01:58:09|120346|JobLog.py   | Work directory size dictionary not created (will create it now)
2016-11-15 01:58:09|120346|FileHandling| Checking size of work dir: /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229
2016-11-15 01:58:09|120346|FileHandling| Size of directory /scratch/Panda_Pilot_120346_1479173221/PandaJob_3078617668_1479173229: 21635072 B
